cat > deploymentsvc.yaml <<'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellodocker
  template:
    metadata:
      labels:
        app: hellodocker
    spec:
      containers:
      - name: hellodocker
        image: ramsesreyes04/hellodocker:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hellodocker-svc
spec:
  type: NodePort
  selector:
    app: hellodocker
  ports:
  - port: 80
    targetPort: 80
EOF
